### ISSUE TITLE
Nuevo error

### ISSUE THREAD

**Issue by MirelSIG** [maestria-geotel-201902/unidad-1-asignacion-2-rasters-y-exportar-datos-espaciales-MirelSIG#2]
![image](https://user-images.githubusercontent.com/39567020/68355638-43e85880-00e6-11ea-9245-e269f0fa3e73.png)

**Comment by geofis** [comment]
@MirelSIG, lo mismo pasa a Wilnellia (pongo aquí a todo el grupo: @maestria-geotel-201902/estudiantes, para que este *issue* sirva a todos).

Noten Mirel y Wilnellia que sus objetos `miprov`, aunque son clase `sf` no tienen datos:

```
miprov
# Simple feature collection with 0 features and 4 fields
# bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
# epsg (SRID):    32619
# proj4string:    +proj=utm +zone=19 +datum=WGS84 +units=m +no_defs
# [1] PROV      REG       TOPONIMIA ENLACE    geom     
# <0 rows> (or 0-length row.names)
```

Donde pone `0 rows` significa que no contiene ningún *features*. 

El problema viene de antes:

```
miprov <- prov[prov$'PROVCenso2010' %in% '13', ]
```

No hay una columna `PROVCenso2010` dentro de `prov`. Lo que existe es una capa del archivo `GPKG` que se llamaba así. La columna que corresponde colocar es `PROV`. Sería algo tal que:

```
miprov <- prov[prov$PROV %in% '13', ]
```

Por otra parte, en el caso específico de Mirel, tienes código fuera de bloque de código entre las líneas 83 y 89 del archivo `README.Rmd`. Ese código debería colocarse dentro bloque de código. Si no lo haces, no podrás tejer adecuadamente el documento.
